# Generated by Django 3.2.12 on 2024-05-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
